import type { Metadata } from "next";
import "@/styles/globals.css";
import Navbar from "@/component/Navbar";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default  function RootLayout({
  children,
  // params,
}: Readonly<{
  children: React.ReactNode;
  // params: { locale: string };
}>) {
  return (
    <html lang={"en"}>
      <head>
        <Script
          async
          src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID}`}
        />
        <Script id="ga-init" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', '${process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID}', {
              page_path: window.location.pathname,
            });
          `}
        </Script>
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-LRJXKP1N7W"></script>
      </head>
      <body
        className={`antialiased bg-[#F3F4F6] text-[16px] text-normal font-sf-pro text-black`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
