import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/component/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-[#F3F4F6] text-[16px] text-normal font-sf-pro text-black`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
